CREATE DATABASE IF NOT EXISTS encurtadordb;

USE encurtadordb;

CREATE TABLE IF NOT EXISTS urlencurtadas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    url VARCHAR(255) NOT NULL,
    shortedUrl VARCHAR(255) NOT NULL,
    date DATE DEFAULT NOW()
);